export const USER_GET_REQUEST = "USER_GET_REQUEST";
export const USER_GET_SUCCESS = "USER_GET_SUCCESS";
export const USER_GET_FAILURE = "USER_GET_FAILURE";

export const USER_CLEAR = "USER_CLEAR";

export const MODAL_GROUPS_SET_SHOW = "MODAL_GROUPS_SET_SHOW";
export const MODAL_INVITE_GROUP_SET_SHOW = "MODAL_INVITE_GROUP_SET_SHOW";
export const MODAL_JOIN_GROUP_SET_SHOW = "MODAL_JOIN_GROUP_SET_SHOW";
export const MODAL_NEW_GROUP_SET_SHOW = "MODAL_NEW_GROUP_SET_SHOW";

export const SELECTED_SET_GROUP = "SELECTED_SET_GROUP";
export const SELECTED_SET_LIST = "SELECTED_SET_LIST";
export const SELECTED_SET_TASK = "SELECTED_SET_TASK";
